# Generated by Django 2.0.2 on 2018-03-01 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_introduced', models.IntegerField()),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Syllabus'),
        ),
        migrations.AddField(
            model_name='lab',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Subject'),
        ),
    ]
